---
- name: Install Nginx site
  template: src=momentum-frontend.conf.j2 dest=/etc/nginx/sites-available/momentum-frontend.conf owner=root group=root mode=0644
  notify: Restart Nginx

- name: Enable the site
  file: path=/etc/nginx/sites-enabled/momentum-frontend.conf src=/etc/nginx/sites-available/momentum-frontend.conf state=link owner=root group=root mode=0644
  notify: Restart Nginx
